version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: NodeJS version
          command: node --version
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: ESlint
          command: yarn run test:eslint
      - run:
          name: Stylelint
          command: yarn run test:stylelint

  build:
    environment:
      IMAGE_NAME: melvinversluijs/react-wp-theme
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build --tag=$IMAGE_NAME:latest .
      - run:
          name: Publish Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

  deploy:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - run:
          name: Deploy new Docker image to production
          command: |
            ssh -v -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST \
              "docker stack deploy -c $DOCKER_STACK_FILE $DOCKER_STACK_NAME"

workflows:
  version: 2
  test_build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
